### ISSUE TITLE
Es fehlen funktionierende IR Sensoren für einige Richtungen

### ISSUE THREAD

**Issue by theBrainsGD** [theBrainsGD/Rescue_Maze_Entry#1]
Der Roboter hat aktuell drei funktionierende IR Sensoren. Davon sind zwei nach vorn und einer nach links ausgerichtet. Um richtig funktionieren zu können muss der Roboter allerdings mindestens einen Sensor nach rechts nachgerüstet bekommen, sonst funktioniert das ganze Programm nicht und die Karte muss mehr oder weniger verworfen werden!

**Comment by JayPi4c** [comment]
Es wurden neue Sensoren hinzugefügt! Es sind zwei Sensoren nach vorne gerichtet, zwei nach links und einer nach rechts. In jede Richtung gibt es immer einen Sharp Sensor, der eine Reichweite zwischen 4 und 30 cm hat und nach vorne und nach links sind auch noch jeweils Sensoren mit einer Reichweite von 10 bis 80 cm  angebracht.

**Comment by JayPi4c** [comment]
Nach dem RoboCup haben sich die neuen Sensoren als gut erwiesen. An den Positionen bieten sie sich sehr gut an.
Hiermit schließe den Issue!
